2019-11-19 17:47:56,773 file.manager INFO 1.2.0
2019-11-19 17:47:56,773 file.manager INFO Copyright (C) 2003-2010
2019-11-19 17:47:56,773 file.manager INFO   Noriaki Ando
2019-11-19 17:47:56,773 file.manager INFO   Intelligent Systems Research Institute, AIST
2019-11-19 17:47:56,775 file.manager INFO Manager starting.
2019-11-19 17:47:56,775 file.manager INFO Starting local logging.
2019-11-19 17:47:56,779 file.manager.namingmanager INFO NameServer connection succeeded: corba/localhost
2019-11-19 17:47:58,805 file.ManagerServant INFO Master manager not found
2019-11-19 17:47:58,811 file.LocalServiceAdmin INFO All the local services are enabled.
2019-11-19 17:47:58,812 file.LocalServiceAdmin INFO All the local services are enabled.
2019-11-19 17:47:58,832 file.manager INFO Component type conf file: Human_Tracking_py.conf loaded.
2019-11-19 17:47:58,845 file.ec_base INFO setRate(1000000.000000) done
2019-11-19 17:47:58,845 file.ec_base INFO setRate(100.000000) done
2019-11-19 17:47:58,848 file.rtobject INFO 1 execution context was created.
2019-11-19 17:47:58,861 file.rtobject INFO Initial active configuration set is default.
2019-11-19 17:48:01,539 file.SdoServiceAdmin WARNING No available SDO service in the factory: 
2019-11-19 17:48:01,540 file.SdoServiceAdmin ERROR type  already exists.
2019-11-19 17:48:11,015 file.ManagerServant INFO Master manager not found
2019-11-19 17:48:23,265 file.ManagerServant INFO Master manager not found
2019-11-19 17:48:35,555 file.ManagerServant INFO Master manager not found
2019-11-19 17:48:47,864 file.ManagerServant INFO Master manager not found
2019-11-19 17:48:49,029 file.rtobject ERROR Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\OpenRTM_aist\RTObject.py", line 1571, in on_execute
    ret = self.onExecute(ec_id)
  File "c:\workspace\Human_Tracking_py\Human_Tracking_py.py", line 176, in onExecute
    a=trans_x_y(1000,300)#(self.range_data[i],i)
TypeError: 'NoneType' object is not callable

2019-11-19 17:48:49,033 file.rtobject ERROR Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\OpenRTM_aist\RTObject.py", line 1370, in on_deactivated
    ret = self.onDeactivated(ec_id)
  File "c:\workspace\Human_Tracking_py\Human_Tracking_py.py", line 163, in onDeactivated
    return RTC.RTC_OK
AttributeError: 'NoneType' object has no attribute 'RTC_OK'

2019-11-19 17:48:59,984 file.ManagerServant INFO Master manager not found
2019-11-19 17:49:12,085 file.ManagerServant INFO Master manager not found
