2019-11-20 16:51:19,407 file.manager INFO 1.2.0
2019-11-20 16:51:19,407 file.manager INFO Copyright (C) 2003-2010
2019-11-20 16:51:19,407 file.manager INFO   Noriaki Ando
2019-11-20 16:51:19,408 file.manager INFO   Intelligent Systems Research Institute, AIST
2019-11-20 16:51:19,408 file.manager INFO Manager starting.
2019-11-20 16:51:19,408 file.manager INFO Starting local logging.
2019-11-20 16:51:19,414 file.manager.namingmanager INFO NameServer connection succeeded: corba/localhost
2019-11-20 16:51:21,443 file.ManagerServant INFO Master manager not found
2019-11-20 16:51:21,448 file.LocalServiceAdmin INFO All the local services are enabled.
2019-11-20 16:51:21,450 file.LocalServiceAdmin INFO All the local services are enabled.
2019-11-20 16:51:21,471 file.manager INFO Component type conf file: Human_Tracking_py.conf loaded.
2019-11-20 16:51:21,483 file.ec_base INFO setRate(1000000.000000) done
2019-11-20 16:51:21,484 file.ec_base INFO setRate(100.000000) done
2019-11-20 16:51:21,490 file.rtobject INFO 1 execution context was created.
2019-11-20 16:51:21,503 file.rtobject INFO Initial active configuration set is default.
2019-11-20 16:51:26,010 file.SdoServiceAdmin WARNING No available SDO service in the factory: 
2019-11-20 16:51:26,010 file.SdoServiceAdmin ERROR type  already exists.
2019-11-20 16:51:33,651 file.ManagerServant INFO Master manager not found
2019-11-20 16:51:34,951 file.rtobject ERROR Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\OpenRTM_aist\RTObject.py", line 1571, in on_execute
    ret = self.onExecute(ec_id)
  File "c:\workspace\Human_Tracking_py\Human_Tracking_py.py", line 189, in onExecute
    self.x_seq=r_seq*np.cos(th_seq)
ValueError: operands could not be broadcast together with shapes (800,) (681,) 

2019-11-20 16:51:42,197 file.rtobject ERROR Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\OpenRTM_aist\RTObject.py", line 1571, in on_execute
    ret = self.onExecute(ec_id)
  File "c:\workspace\Human_Tracking_py\Human_Tracking_py.py", line 189, in onExecute
    self.x_seq=r_seq*np.cos(th_seq)
ValueError: operands could not be broadcast together with shapes (800,) (681,) 

2019-11-20 16:51:45,921 file.ManagerServant INFO Master manager not found
2019-11-20 16:51:58,157 file.ManagerServant INFO Master manager not found
2019-11-20 16:52:10,392 file.ManagerServant INFO Master manager not found
2019-11-20 16:52:22,635 file.ManagerServant INFO Master manager not found
2019-11-20 16:52:34,861 file.ManagerServant INFO Master manager not found
2019-11-20 16:52:47,095 file.ManagerServant INFO Master manager not found
2019-11-20 16:52:59,329 file.ManagerServant INFO Master manager not found
